version: '3.2'

services:
 elasticsearch:
   build:
     context: elasticsearch/
   volumes:
     - type: volume
       source: elasticsearch
       target: /usr/share/elasticsearch/data
   ports:
     - "9200:9200"
     - "9300:9300"
   environment:
     ES_JAVA_OPTS: "-Xmx256m -Xms256m"
     ELASTIC_PASSWORD: yourstrongpasswordhere
     discovery.type: single-node
   networks:
     - internal

 logstash:
   build:
     context: logstash/
   ports:
     - "5000:5000"
     - "9600:9600"
   environment:
     LS_JAVA_OPTS: "-Xmx256m -Xms256m"
   networks:
     - internal
   depends_on:
     - elasticsearch

 kibana:
   build:
     context: kibana/
   ports:
     - "5601:5601"
   networks:
     - internal
   depends_on:
     - elasticsearch

networks:
  internal:
    external: true

volumes:
 elasticsearch:
